### ISSUE TITLE
updates to manual needed

### ISSUE THREAD

**Issue by arlin** [nexml/nexml.github.io#6]
The manual was drafted in 2011 and needs an update.  Here is a preliminary list of things to do.  Updates and suggestions are welcome.  
## Informational updates
- Check and update links 
- Update list of applications that support NeXML for input or output 
- Update list of databases and repositories that support NeXML for upload or download 
  - add Open Tree
  - add some stuff from Kew Gardens 
- Update list of programming APIs 
  - Clarify status of NCL support 
## Code examples
- check code examples (dendropy update breaks at least one example)
## New content
- add a discussion of NeXSON 
- provide a list of practical examples of metadata annotation

**Comment by mjy** [comment]
* Link to main page is broken.

**Comment by rvosa** [comment]
Which wiki link is broken? They seem to work for me. For CDAO the question is what to link to now that the original domain has gone offline.

**Comment by rvosa** [comment]
I suppose the CDAO link should either be the git repository or the NCBO page?

**Comment by rvosa** [comment]
Done.

**Comment by arlin** [comment]
Thanks.
